version: '3.8'

services:
  backend_db:
    image: postgres
    container_name: backend_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend_db
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: backend_app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - backend_db
    depends_on:
      - backend_db
volumes:
  pgdata:
    driver: local
